# Generated by Django 4.0.1 on 2022-02-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
